# This is a basic workflow to help understand github actions to deploy snowflake DDL on commit to main branch

name: Deploy DDL changes to Snowflake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  display:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT : ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      #SNOWFLAKE_DOMAINS_DB: ${{ env.SNOWFLAKE_DOMAINS_DB }}
      #SNOWFLAKE_DOMAINS_SCHEMA: ${{ env.SNOWFLAKE_DOMAINS_SCHEMA }}
      #SNOWFLAKE_DOMAINS_GIT_STG: ${{ env.SNOWFLAKE_DOMAINS_GIT_STG }}
      name: Production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # display the env variables
      - name: Display custom env variables
        run: |
          echo "${{ SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT }}"
          echo "${{ SNOWFLAKE_CONNECTIONS_DEFAULT_USER }}"
