# This is a basic workflow to help understand github actions to deploy snowflake DDL on commit to main branch

name: Deploy DDL changes to Snowflake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "display"
  display:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #environment: ${{ github.ref == 'main' && 'Production' || 'Development' }}      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set environment for branch
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
              environment: 'Production'
          else
              environment: 'Development'
          fi
          environment: ${{environment}}   
      # display the env variables
      - name: Display custom env variables
        run: |
          echo "${{ vars.SNOWFLAKE_DOMAINS_DB }}"
